### ISSUE TITLE
MySql.Data.MySqlClient.MySqlException: Unknown column 'this_.StartEpisodeType' in 'field list'

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dizzydezz/jmm#361]
```
Noticed a whole pile of these errors in the log. Not sure if this is due to 
some kind of corrupted install on my side, or an actual error.

[2012-12-18 23:09:52:194] Error|SyncMethodInvoker.Invoke => <no 
type>.SyncInvokeGetAllSeries => JMMServiceImplementation.GetAllSeries 
NHibernate.Exceptions.GenericADOException: could not execute query
[ SELECT this_.CrossRef_AniDB_MALID as CrossRef1_296_0_, this_.AnimeID as 
AnimeID296_0_, this_.CrossRefSource as CrossRef3_296_0_, this_.MALID as 
MALID296_0_, this_.MALTitle as MALTitle296_0_, this_.StartEpisodeType as 
StartEpi6_296_0_, this_.StartEpisodeNumber as StartEpi7_296_0_ FROM 
`CrossRef_AniDB_MAL` this_ ]
[SQL: SELECT this_.CrossRef_AniDB_MALID as CrossRef1_296_0_, this_.AnimeID as 
AnimeID296_0_, this_.CrossRefSource as CrossRef3_296_0_, this_.MALID as 
MALID296_0_, this_.MALTitle as MALTitle296_0_, this_.StartEpisodeType as 
StartEpi6_296_0_, this_.StartEpisodeNumber as StartEpi7_296_0_ FROM 
`CrossRef_AniDB_MAL` this_] ---> MySql.Data.MySqlClient.MySqlException: Unknown 
column 'this_.StartEpisodeType' in 'field list'
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int32& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int32& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
   at NHibernate.AdoNet.AbstractBatcher.ExecuteReader(IDbCommand cmd) in d:\CSharp\NH\nhibernate\src\NHibernate\AdoNet\AbstractBatcher.cs:line 247
   at NHibernate.Loader.Loader.GetResultSet(IDbCommand st, Boolean autoDiscoverTypes, Boolean callable, RowSelection selection, ISessionImplementor session) in d:\CSharp\NH\nhibernate\src\NHibernate\Loader\Loader.cs:line 1337
   at NHibernate.Loader.Loader.DoQuery(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies) in d:\CSharp\NH\nhibernate\src\NHibernate\Loader\Loader.cs:line 401
   at NHibernate.Loader.Loader.DoQueryAndInitializeNonLazyCollections(ISessionImplementor session, QueryParameters queryParameters, Boolean returnProxies) in d:\CSharp\NH\nhibernate\src\NHibernate\Loader\Loader.cs:line 236
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters) in d:\CSharp\NH\nhibernate\src\NHibernate\Loader\Loader.cs:line 1665
   --- End of inner exception stack trace ---
   at NHibernate.Loader.Loader.DoList(ISessionImplementor session, QueryParameters queryParameters) in d:\CSharp\NH\nhibernate\src\NHibernate\Loader\Loader.cs:line 1674
   at NHibernate.Loader.Loader.ListIgnoreQueryCache(ISessionImplementor session, QueryParameters queryParameters) in d:\CSharp\NH\nhibernate\src\NHibernate\Loader\Loader.cs:line 1589
   at NHibernate.Loader.Loader.List(ISessionImplementor session, QueryParameters queryParameters, ISet`1 querySpaces, IType[] resultTypes) in d:\CSharp\NH\nhibernate\src\NHibernate\Loader\Loader.cs:line 1579
   at NHibernate.Impl.SessionImpl.List(CriteriaImpl criteria, IList results) in d:\CSharp\NH\nhibernate\src\NHibernate\Impl\SessionImpl.cs:line 1920
   at NHibernate.Impl.CriteriaImpl.List(IList results) in d:\CSharp\NH\nhibernate\src\NHibernate\Impl\CriteriaImpl.cs:line 246
   at NHibernate.Impl.CriteriaImpl.List[T]() in d:\CSharp\NH\nhibernate\src\NHibernate\Impl\CriteriaImpl.cs:line 257
   at JMMServer.Repositories.CrossRef_AniDB_MALRepository.GetAll() in C:\Projects\SVN\JMM\trunk\JMMServer\JMMServer\Repositories\CrossRef_AniDB_MALRepository.cs:line 80
   at JMMServer.JMMServiceImplementation.GetAllSeries(Int32 userID) in C:\Projects\SVN\JMM\trunk\JMMServer\JMMServer\JMMServiceImplementation.cs:line 1948
```

Original issue reported on code.google.com by `gl...@ensquared.net` on 18 Dec 2012 at 12:15

**Comment by GoogleCodeExporter** [comment]
```
No idea why this got listed as enhancement.. I definitely selected bug *sigh*

Also, here is the log file.
```

Original comment by `gl...@ensquared.net` on 18 Dec 2012 at 12:51

Attachments:
- [2012-12-18.txt](https://storage.googleapis.com/google-code-attachments/jmm/issue-361/comment-1/2012-12-18.txt)

**Comment by GoogleCodeExporter** [comment]
Original comment by `werndly...@gmail.com` on 18 Dec 2012 at 10:37
- Changed state: **Accepted**
- Added labels: **Product-JMM**, **Type-Defect**
- Removed labels: **Type-Enhancement**

**Comment by GoogleCodeExporter** [comment]
Original comment by `werndly...@gmail.com` on 21 Dec 2012 at 2:35
- Added labels: **Priority-High**
- Removed labels: **Priority-Medium**

**Comment by GoogleCodeExporter** [comment]
```
It looks like the version of MySQL you are using is case sensitive when it 
comes to sql statements.

Did you already have a pre-installed version?
```

Original comment by `werndly...@gmail.com` on 21 Dec 2012 at 2:48

**Comment by GoogleCodeExporter** [comment]
```
I'm using the latest version available for my thecus NAS. Will double check
the version and get back to you.

On Friday, December 21, 2012, wrote:
```

Original comment by `gl...@ensquared.net` on 22 Dec 2012 at 10:07

**Comment by GoogleCodeExporter** [comment]
```
Looks like I'm running MySQL 5.1.45
```

Original comment by `gl...@ensquared.net` on 23 Dec 2012 at 10:57

**Comment by GoogleCodeExporter** [comment]
```
Ah yes, I have had quite a few people who have issues with older MySQL versions 
running on devices.

I don't think this can be fixed unless you are willing to run MySQL 5.5 
somewhere else (or another database)
```

Original comment by `werndly...@gmail.com` on 23 Dec 2012 at 10:30

**Comment by GoogleCodeExporter** [comment]
```
Hrmm, that's a pain. Ah well, looks like I'll be looking into upgrading it :)

I'm assuming there's no way/no easy way to make it run on earlier
versions? If not, would it be possible to include a check in the
database initialise script, and throw an error if it's an unsupported
version of MySQL?

- Glenn
```

Original comment by `gl...@ensquared.net` on 24 Dec 2012 at 5:43

**Comment by GoogleCodeExporter** [comment]
```
You dont need to update MySQL just need to change the collation of the 
database, read the following.

See for example this:
http://stackoverflow.com/questions/4879846/how-to-configure-mysql-to-be-case-sen
sitive

It should be something like:
CREATE DATABASE test_database CHARACTER SET utf8 COLLATE utf8_general_ci;
```

Original comment by `buzzplay...@gmail.com` on 3 Jan 2013 at 10:08

**Comment by GoogleCodeExporter** [comment]
```
Thanks a lot for that info
```

Original comment by `werndly...@gmail.com` on 3 Jan 2013 at 11:48

**Comment by GoogleCodeExporter** [comment]
```
I've also got this issue.

I let JMM create the database using root credentials on my 5.6.19 MySQL 
instance, and my logs have grown to over 100MB filled with this error. 
Performance is also very, very slow as it runs general tasks.

Confirmed via phpmyadmin that the collate is set to utf8_general_ci
```

Original comment by `Clockwor...@gmail.com` on 6 Jul 2014 at 3:45

**Comment by GoogleCodeExporter** [comment]
```
https://github.com/japanesemediamanager/jmmserver/issues/17
```

Original comment by `werndly...@gmail.com` on 19 Aug 2014 at 6:55
- Changed state: **Migrated**
