### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dizzydezz/jmm#436]
```
JMM Server can sometimes spam out error messages relating to a null object 
reference with the connection.

log attached.

Error example

Error|AniDBHelper.Login => AniDBCommand_Login.Process => 
AniDBUDPCommand.ProcessCommand System.ArgumentNullException: Value cannot be 
null.
Parameter name: remoteEP
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, EndPoint remoteEP)
   at AniDBAPI.Commands.AniDBUDPCommand.ProcessCommand(Socket& soUDP, IPEndPoint& remoteIpEndPoint, String sessionID, Encoding enc) in C:\Projects\SVN\JMM\trunk\JMMServer\JMMServer\AniDB_API\Commands\AniDBUDPCommand.cs:line 105
```

Original issue reported on code.google.com by `Craige1Emmott` on 17 May 2013 at 1:54

Attachments:
- [2013-05-17.txt](https://storage.googleapis.com/google-code-attachments/jmm/issue-436/comment-0/2013-05-17.txt)

**Comment by GoogleCodeExporter** [comment]
```
https://github.com/japanesemediamanager/jmmserver/issues/58
```

Original comment by `werndly...@gmail.com` on 19 Aug 2014 at 10:50
- Changed state: **Migrated**
