### ISSUE TITLE
401 Unauthorized Error During Import

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dizzydezz/jmm#532]
```
What steps will reproduce the problem?
1. Add any file to the drop source
2. profit
3.

What is the expected output? What do you see instead?
File is synced and moved accordingly

What version of the product are you using? On what operating system?
3.1.32 on Windows 8.1 Update 1

Please provide any additional information below.
Is there a way to disable TraktTV service? I seem to be getting a lot of errors 
which causes the whole process to crap out and none of my files get moved and 
dropped in the drop destination folders properly.

```

Original issue reported on code.google.com by `A.Akker...@gmail.com` on 8 Sep 2014 at 1:55

**Comment by GoogleCodeExporter** [comment]
```
[2014-09-07 21:53:03:700] 
Error|CommandRequest_TraktSyncCollectionSeries.ProcessCommand => 
TraktTVHelper.SyncCollectionToTrakt_Series => TraktTVHelper.SendData Error(1) 
in XMLServiceQueue.SendData: System.Net.WebException: The remote server 
returned an error: (401) Unauthorized.
   at System.Net.HttpWebRequest.GetResponse()
   at JMMServer.Providers.TraktTV.TraktTVHelper.SendData(String uri, String json) in C:\Projects\SVN\JMM\trunk\JMMServer\JMMServer\Providers\TraktTV\TraktTVHelper.cs:line 1017

Relevant error.
```

Original comment by `A.Akker...@gmail.com` on 8 Sep 2014 at 1:55
